/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
Lista de paquetes:
 */
package ud2_ejer04.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import ud2_ejer04.gui.dibujos.Fondo;
import ud2_ejer04.gui.dibujos.Persona;

/**
 * Dibuja el fondo y la persona pasandoles la fase de la animacion.
 * Tambien se crea un transformador original que sirve para resetear transformaciones
 * cuando haga falta durante los dibujados. Se recalcula en cada repintado porque 
 * cambia dependiendo de la densidad de pixeles de la pantalla.
 * 
 * @author Jose Javier Bailon Ortiz
 * @see Fondo
 * @see Persona
 */
public class Lienzo extends javax.swing.JPanel {

    /**
     * Transformacion para resetear. Se recalcula a cada repintado porque cambia
     * dependiendo de la densidad de pixeles de la pantalla.
     */
    public static AffineTransform resetTransform;
    
    /**
     * referencia al dibujo fondo
     */
    private final Fondo fondo = new Fondo(0, 0);
    
    /**
     * referencia al dibujo persona
     */
    private final Persona persona = new Persona(-60, 460);

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }

    /**
     * Cada vez que se pinta el componente se actualiza la fase de los dibujos
     * y se pintan.
     * @param g 
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        //crear el transformador origen
        resetTransform = g2d.getTransform();
        
        //dibujar fondo
        fondo.setFase(Ventana.fase);
        fondo.dibujar(g2d);
        
        //dibujar persona
        persona.setFase(Ventana.fase);
        persona.dibujar(g2d);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
